name: Weekly Leaderboard Bot

on:
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00 UTC
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows committing changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Grants write access

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r bot/requirements.txt

      - name: Run Leaderboard Scraper
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          DISCUSSION_CATEGORY_ID: ${{ secrets.DISCUSSION_CATEGORY_ID }}
        run: python bot/bot.py
